/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Encoder {
  A = 0
}
/**
 * A Signal struct without the Input Payload.
 *
 * This is useful for routing webhook events back to the workflow,
 * and the event itself will be sent as the Signal's Input to the workflow.
 */
export interface TemporalSignalWithoutInput {
  namespace: string
  taskQueue: string
  workflowId?: string
  runId?: string
  signalName: string
}
/**
 * Convert workflow metadata into an encoded string for embedding into a webhook event, using the default encoding.
 *
 * Example: use this string as the `callback_id` for a slack interaction, and when
 * the Temporal API Gateway receives the event it can decode the string and route the event to your workflow.
 */
export function encodeSignalNoArgsDefault(signal: TemporalSignalWithoutInput): string
/**
 * Convert workflow metadata into an encoded string for embedding into a webhook event, with a specific encoding version.
 *
 * Example: use this string as the `callback_id` for a slack interaction, and when
 * the Temporal API Gateway receives the event it can decode the string and route the event to your workflow.
 */
export function encodeSignalNoArgsWithVersion(encoderVersion: Encoder, signal: TemporalSignalWithoutInput): string
/**
 * Encode a TemporalInteraction struct provided as a JSON string.
 *
 * panics if JSON structure is not correct.
 */
export function encodeDefaultFromJsonString(jsonString: string): string
/** Decode an encoded string into a JSON string representing a TemporalInteraction struct. */
export function decodeToJsonString(encodedString: string): string
