version: "3.5"

services:
  temporal_apig:
    build:
      dockerfile: "Dockerfile.apig"

    ## interactive mode for debugging
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    # entrypoint: "/bin/sh"

    env_file: .default.env
    ports:
      - 3000:3000
    environment:
      # overwrite localhost because of dockercompose
      TEMPORAL_SERVICE_HOST: host.docker.internal

      # Deployment Secrets
      # SECRET_MY_SECRET_NAME: secrets/my_secret_name
